[package]
name = "kernel"
version = "0.1.1"
authors = ["Maxim Sokhatskyi <maxim@synrc.com>"]
license = "MIT"
repository = "https://github.com/AlgoTradingHub/kernel"
homepage = "https://github.com/AlgoTradingHub/kernel"
documentation = "http://5ht.co/kernel.htm"
description = """
Abstract Reactive Streams
"""

[[bin]]
name = "fix"
path = "src/apps/fix.rs"

[[bin]]
name = "client"
path = "src/apps/client.rs"

[[bin]]
name = "server"
path = "src/apps/server.rs"

[dependencies]
net2     = "0.2.19"
log = "0.3"
mio = "0.6"
rand = "*"
slab = "0.3"
bitflags = "0.4"

[target.'cfg(unix)'.dependencies]
nix    = "0.6.0"
libc   = "0.2.14"
